In [ ]:
!wget https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv

--2021-11-15 16:13:56--  https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv
Resolving gist.githubusercontent.com (gist.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to gist.githubusercontent.com (gist.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3858 (3.8K) [text/plain]
Saving to: ‘iris.csv’

iris.csv            100%[===================>]   3.77K  --.-KB/s    in 0s      

2021-11-15 16:13:56 (48.1 MB/s) - ‘iris.csv’ saved [3858/3858]



In [ ]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression

In [ ]:
df = pd.read_csv('/content/iris.csv')
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
df.shape

(150, 5)

In [ ]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [ ]:
df.isna().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [ ]:
df.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le = LabelEncoder()

In [ ]:
df['species'] = le.fit_transform(df['species'])

In [ ]:
le_name_mapping = dict(zip(le.classes_, le.transform(le.classes_)))


In [ ]:
df

sepal_length  sepal_width  petal_length  petal_width  species
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

[150 rows x 5 columns]

In [ ]:
150 * 0.8

120.0

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1:]

In [ ]:
x_train,x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [ ]:
x_train

sepal_length  sepal_width  petal_length  petal_width
120           6.9          3.2           5.7          2.3
40            5.0          3.5           1.3          0.3
44            5.1          3.8           1.9          0.4
92            5.8          2.6           4.0          1.2
12            4.8          3.0           1.4          0.1
..            ...          ...           ...          ...
17            5.1          3.5           1.4          0.3
112           6.8          3.0           5.5          2.1
119           6.0          2.2           5.0          1.5
132           6.4          2.8           5.6          2.2
102           7.1          3.0           5.9          2.1

[120 rows x 4 columns]

In [ ]:
y_train

species
120        2
40         0
44         0
92         1
12         0
..       ...
17         0
112        2
119        2
132        2
102        2

[120 rows x 1 columns]

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
lg_model = LogisticRegression()

In [ ]:
lg_model.fit(x_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
x_test

sepal_length  sepal_width  petal_length  petal_width
87            6.3          2.3           4.4          1.3
146           6.3          2.5           5.0          1.9
93            5.0          2.3           3.3          1.0
42            4.4          3.2           1.3          0.2
53            5.5          2.3           4.0          1.3
70            5.9          3.2           4.8          1.8
56            6.3          3.3           4.7          1.6
80            5.5          2.4           3.8          1.1
116           6.5          3.0           5.5          1.8
143           6.8          3.2           5.9          2.3
68            6.2          2.2           4.5          1.5
78            6.0          2.9           4.5          1.5
9             4.9          3.1           1.5          0.1
121           5.6          2.8           4.9          2.0
61            5.9          3.0           4.2          1.5
127           6.1          3.0           4.9          1.8
49            5.0          3.3           1.4          0.2
145           6.7          3.0           5.2          2.3
24            4.8          3.4           1.9          0.2
23            5.1          3.3           1.7          0.5
76            6.8          2.8           4.8          1.4
15            5.7          4.4           1.5          0.4
140           6.7          3.1           5.6          2.4
45            4.8          3.0           1.4          0.3
104           6.5          3.0           5.8          2.2
88            5.6          3.0           4.1          1.3
84            5.4          3.0           4.5          1.5
110           6.5          3.2           5.1          2.0
101           5.8          2.7           5.1          1.9
46            5.1          3.8           1.6          0.2

In [ ]:
pred = lg_model.predict(x_test)

In [ ]:
pred

array([1, 2, 1, 0, 1, 2, 1, 1, 2, 2, 1, 1, 0, 2, 1, 2, 0, 2, 0, 0, 1, 0,
       2, 0, 2, 1, 1, 2, 2, 0])

In [ ]:
import numpy as np

In [ ]:
np.squeeze(y_test.values,axis=1)

array([1, 2, 1, 0, 1, 1, 1, 1, 2, 2, 1, 1, 0, 2, 1, 2, 0, 2, 0, 0, 1, 0,
       2, 0, 2, 1, 1, 2, 2, 0])

In [ ]:
lg_model.predict(np.array([[1.4,2.3,1.3,1.3]]))

array([0])

In [ ]:
le_name_mapping

{'setosa': 0, 'versicolor': 1, 'virginica': 2}